version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: "redis:latest"
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dev.Dockerfile
    image: apshuk21/arch-nginx
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - api
      - client
  api:
    build:
      context: ./server
      dockerfile: Dev.Dockerfile
    image: apshuk21/arch-api
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dev.Dockerfile
    image: apshuk21/arch-client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  worker:
    build:
      context: ./worker
      dockerfile: Dev.Dockerfile
    image: apshuk21/arch-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
